var Ghost = require('../js/lib/Ghost/Ghost.js');

describe("Ghost", function () {
  it("returns an object when called", function () {
    expect(Ghost()).toEqual(jasmine.any(Object));
  });
  it("", function() {
    expect(Ghost()).toEqual(jasmine.any(Object));
  });
});

describe("ghost: generated by Ghost with arity 1 and length 8", function () {
  var ghost;
  beforeEach(function() {
    ghost = Ghost(1, 8);
  });
  it("has a chromosomes property which is an array", function () {
    expect(ghost.chromosomes).toEqual(jasmine.any(Array));
  });
  it("has a chromosomes property which is an array of length 2", function () {
    expect(ghost.chromosomes.length).toEqual(2);
  });
  it("has chromosomes[0].length = 8", function () {
    expect(ghost.chromosomes[0].length).toEqual(8);
  });
  it("has chromosomes[1].length = 8", function () {
    expect(ghost.chromosomes[1].length).toEqual(8);
  });
});
